from __future__ import annotations

from contextlib import contextmanager
from datetime import date, datetime
import re
from typing import Any, Iterable
from urllib.parse import unquote, urlparse


POSTGRES_SCHEMES = ("postgresql://", "postgres://")
_TIMESTAMP_COLUMNS = {
    "created_at", "updated_at", "expires_at", "last_sent_at", "window_started_at",
    "sent_at", "read_at", "deleted_at", "last_read_at",
}


class DatabaseIntegrityError(Exception):
    """Lỗi ràng buộc dữ liệu PostgreSQL đã được chuẩn hóa cho tầng nghiệp vụ."""


def is_postgres_target(target: Any) -> bool:
    return isinstance(target, str) and target.strip().lower().startswith(POSTGRES_SCHEMES)


def require_postgres_target(target: Any) -> str:
    value = str(target or "").strip()
    if not is_postgres_target(value):
        raise RuntimeError(
            "DOMIX chỉ sử dụng PostgreSQL. Hãy chạy bằng docker compose và không truyền đường dẫn database dạng file."
        )
    return value


def database_backend(target: Any) -> str:
    require_postgres_target(target)
    return "postgresql"


def database_identity(target: Any) -> str:
    """Tên kết nối an toàn để ghi log, tuyệt đối không chứa mật khẩu."""
    parsed = urlparse(require_postgres_target(target))
    host = parsed.hostname or "unknown-host"
    port = parsed.port or 5432
    name = unquote((parsed.path or "/domix").lstrip("/")) or "domix"
    return f"{name}@{host}:{port}"


def _replace_qmark_placeholders(sql: str) -> str:
    """Đổi placeholder nội bộ ``?`` sang ``%s`` mà không chạm chuỗi SQL."""
    output: list[str] = []
    quote = ""
    index = 0
    while index < len(sql):
        char = sql[index]
        if quote:
            output.append("%%" if char == "%" else char)
            if char == quote:
                if index + 1 < len(sql) and sql[index + 1] == quote:
                    output.append(sql[index + 1])
                    index += 1
                else:
                    quote = ""
        elif char in {"'", '"'}:
            quote = char
            output.append(char)
        elif char == "?":
            output.append("%s")
        elif char == "%":
            output.append("%%")
        else:
            output.append(char)
        index += 1
    return "".join(output)


def _append_on_conflict_do_nothing(sql: str) -> str:
    upper = sql.upper()
    if "ON CONFLICT" in upper:
        return sql
    returning_match = re.search(r"\s+RETURNING\s+", sql, flags=re.IGNORECASE)
    if returning_match:
        start = returning_match.start()
        return f"{sql[:start].rstrip()} ON CONFLICT DO NOTHING {sql[start:].lstrip()}"
    return f"{sql.rstrip().rstrip(';')} ON CONFLICT DO NOTHING"


def _translate_postgres_sql(sql: str) -> str:
    """Chuẩn hóa cú pháp SQL lịch sử sang PostgreSQL tại một điểm duy nhất."""
    translated = sql
    translated = re.sub(
        r"datetime\(\s*'now'\s*,\s*'\-1 hour'\s*\)",
        "(CURRENT_TIMESTAMP - INTERVAL '1 hour')",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"datetime\(\s*'now'\s*,\s*\?\s*\)",
        "(CURRENT_TIMESTAMP + (? )::interval)",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"datetime\(\s*'now'\s*\)",
        "CURRENT_TIMESTAMP",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"datetime\(\s*\?\s*\)",
        "CAST(? AS TIMESTAMP)",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        translated,
        flags=re.IGNORECASE,
    )
    for column in _TIMESTAMP_COLUMNS:
        translated = re.sub(
            rf"\b{re.escape(column)}\s+TEXT\b",
            f"{column} TIMESTAMP",
            translated,
            flags=re.IGNORECASE,
        )
    translated = re.sub(r"\s+COLLATE\s+NOCASE\b", "", translated, flags=re.IGNORECASE)

    insert_ignore = bool(re.search(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", translated, flags=re.IGNORECASE))
    translated = re.sub(
        r"\bINSERT\s+OR\s+IGNORE\s+INTO\b",
        "INSERT INTO",
        translated,
        flags=re.IGNORECASE,
    )
    if insert_ignore:
        translated = _append_on_conflict_do_nothing(translated)

    return _replace_qmark_placeholders(translated)


def _normalise_db_value(value: Any) -> Any:
    if isinstance(value, datetime):
        return value.replace(tzinfo=None).strftime("%Y-%m-%d %H:%M:%S")
    if isinstance(value, date):
        return value.isoformat()
    return value


def _normalise_row(row: Any) -> Any:
    if row is None:
        return None
    if isinstance(row, dict):
        return {key: _normalise_db_value(value) for key, value in row.items()}
    return row


class PostgresCursorAdapter:
    def __init__(self, cursor):
        self._cursor = cursor

    @property
    def rowcount(self):
        return self._cursor.rowcount

    def fetchone(self):
        return _normalise_row(self._cursor.fetchone())

    def fetchall(self):
        return [_normalise_row(row) for row in self._cursor.fetchall()]


class PostgresConnectionAdapter:
    backend_name = "postgresql"

    def __init__(self, connection):
        self._connection = connection

    def execute(self, sql: str, params: Iterable[Any] | None = None):
        translated = _translate_postgres_sql(sql)
        try:
            cursor = self._connection.execute(translated, tuple(params or ()))
        except Exception as exc:
            try:
                from psycopg import errors
            except ImportError:
                errors = None
            if errors is not None and isinstance(exc, errors.IntegrityError):
                raise DatabaseIntegrityError(str(exc)) from exc
            raise
        return PostgresCursorAdapter(cursor)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def configure_database(target):
    require_postgres_target(target)
    try:
        import psycopg  # noqa: F401
    except ImportError as exc:
        raise RuntimeError(
            "PostgreSQL yêu cầu package psycopg. Hãy chạy DOMIX bằng docker compose up -d --build."
        ) from exc


@contextmanager
def connect(target):
    target = require_postgres_target(target)
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as exc:
        raise RuntimeError(
            "PostgreSQL yêu cầu package psycopg. Hãy chạy DOMIX bằng docker compose up -d --build."
        ) from exc

    raw = psycopg.connect(target, row_factory=dict_row, connect_timeout=10)
    conn = PostgresConnectionAdapter(raw)
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def table_exists(conn, table_name: str) -> bool:
    row = conn.execute(
        """
        SELECT 1 AS found
        FROM information_schema.tables
        WHERE table_schema = current_schema() AND table_name = ?
        """,
        (table_name,),
    ).fetchone()
    return bool(row)


def table_columns(conn, table_name: str) -> list[str]:
    rows = conn.execute(
        """
        SELECT column_name AS name
        FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = ?
        ORDER BY ordinal_position
        """,
        (table_name,),
    ).fetchall()
    return [row["name"] for row in rows]
