from __future__ import annotations

from contextlib import contextmanager
from datetime import date, datetime
from pathlib import Path
import re
import sqlite3
from typing import Any, Iterable


BUSY_TIMEOUT_MS = 10000
POSTGRES_SCHEMES = ("postgresql://", "postgres://")
_TIMESTAMP_COLUMNS = {
    "created_at", "updated_at", "expires_at", "last_sent_at", "window_started_at",
    "sent_at", "read_at", "deleted_at", "last_read_at",
}


class DatabaseIntegrityError(Exception):
    """Lỗi ràng buộc dữ liệu dùng chung cho SQLite và PostgreSQL."""


def is_postgres_target(target: Any) -> bool:
    return isinstance(target, str) and target.strip().lower().startswith(POSTGRES_SCHEMES)


def database_backend(target: Any) -> str:
    return "postgresql" if is_postgres_target(target) else "sqlite"


def _sqlite_path(target: Any) -> Path:
    if isinstance(target, Path):
        return target
    value = str(target or "").strip()
    if value.startswith("sqlite:///"):
        value = value.removeprefix("sqlite:///")
    return Path(value)


def _replace_qmark_placeholders(sql: str) -> str:
    """Đổi placeholder SQLite ? sang %s, không chạm dấu ? bên trong chuỗi SQL.

    Mọi ký tự % có sẵn trong SQL (VD: LIKE '%kế toán%') được nhân đôi thành %%.
    psycopg luôn parse SQL tìm placeholder ngay khi có truyền params (kể cả tuple
    rỗng) và chỉ chấp nhận %s/%b/%t — một dấu % đơn lẻ còn lại (VD %k trong
    '%kế toán%') làm toàn bộ câu lệnh vỡ với lỗi "only '%s', '%b', '%t' are
    allowed as placeholders". Codebase chỉ dùng ? để bind tham số nên không có
    %s hợp lệ nào cần giữ nguyên trong SQL gốc.
    """
    output: list[str] = []
    quote = ""
    index = 0
    while index < len(sql):
        char = sql[index]
        if quote:
            output.append("%%" if char == "%" else char)
            if char == quote:
                if index + 1 < len(sql) and sql[index + 1] == quote:
                    output.append(sql[index + 1])
                    index += 1
                else:
                    quote = ""
        elif char in {"'", '"'}:
            quote = char
            output.append(char)
        elif char == "?":
            output.append("%s")
        elif char == "%":
            output.append("%%")
        else:
            output.append(char)
        index += 1
    return "".join(output)


def _append_on_conflict_do_nothing(sql: str) -> str:
    upper = sql.upper()
    if "ON CONFLICT" in upper:
        return sql
    returning_match = re.search(r"\s+RETURNING\s+", sql, flags=re.IGNORECASE)
    if returning_match:
        start = returning_match.start()
        return f"{sql[:start].rstrip()} ON CONFLICT DO NOTHING {sql[start:].lstrip()}"
    return f"{sql.rstrip().rstrip(';')} ON CONFLICT DO NOTHING"


def _translate_postgres_sql(sql: str) -> str:
    translated = sql

    # Cú pháp thời gian đặc thù SQLite.
    translated = re.sub(
        r"datetime\(\s*'now'\s*,\s*'\-1 hour'\s*\)",
        "(CURRENT_TIMESTAMP - INTERVAL '1 hour')",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"datetime\(\s*'now'\s*,\s*\?\s*\)",
        "(CURRENT_TIMESTAMP + (? )::interval)",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"datetime\(\s*'now'\s*\)",
        "CURRENT_TIMESTAMP",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"datetime\(\s*\?\s*\)",
        "CAST(? AS TIMESTAMP)",
        translated,
        flags=re.IGNORECASE,
    )

    # DDL tương thích PostgreSQL.
    translated = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        translated,
        flags=re.IGNORECASE,
    )
    for column in _TIMESTAMP_COLUMNS:
        translated = re.sub(
            rf"\b{re.escape(column)}\s+TEXT\b",
            f"{column} TIMESTAMP",
            translated,
            flags=re.IGNORECASE,
        )

    translated = re.sub(r"\s+COLLATE\s+NOCASE\b", "", translated, flags=re.IGNORECASE)

    insert_ignore = bool(re.search(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", translated, flags=re.IGNORECASE))
    translated = re.sub(
        r"\bINSERT\s+OR\s+IGNORE\s+INTO\b",
        "INSERT INTO",
        translated,
        flags=re.IGNORECASE,
    )
    if insert_ignore:
        translated = _append_on_conflict_do_nothing(translated)

    return _replace_qmark_placeholders(translated)


def _normalise_db_value(value: Any) -> Any:
    if isinstance(value, datetime):
        # Giữ định dạng tương thích dữ liệu SQLite và các hàm parse hiện tại.
        return value.replace(tzinfo=None).strftime("%Y-%m-%d %H:%M:%S")
    if isinstance(value, date):
        return value.isoformat()
    return value


def _normalise_row(row: Any) -> Any:
    if row is None:
        return None
    if isinstance(row, dict):
        return {key: _normalise_db_value(value) for key, value in row.items()}
    return row


class PostgresCursorAdapter:
    def __init__(self, cursor):
        self._cursor = cursor

    @property
    def rowcount(self):
        return self._cursor.rowcount

    def fetchone(self):
        return _normalise_row(self._cursor.fetchone())

    def fetchall(self):
        return [_normalise_row(row) for row in self._cursor.fetchall()]


class PostgresConnectionAdapter:
    backend_name = "postgresql"

    def __init__(self, connection):
        self._connection = connection

    def execute(self, sql: str, params: Iterable[Any] | None = None):
        translated = _translate_postgres_sql(sql)
        try:
            cursor = self._connection.execute(translated, tuple(params or ()))
        except Exception as exc:  # psycopg được import động để SQLite không phụ thuộc package này.
            try:
                from psycopg import errors
                if isinstance(exc, errors.IntegrityError):
                    raise DatabaseIntegrityError(str(exc)) from exc
            except ImportError:
                pass
            raise
        return PostgresCursorAdapter(cursor)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


class SQLiteConnectionAdapter:
    backend_name = "sqlite"

    def __init__(self, connection):
        self._connection = connection

    def execute(self, sql: str, params: Iterable[Any] | None = None):
        try:
            return self._connection.execute(sql, tuple(params or ()))
        except sqlite3.IntegrityError as exc:
            raise DatabaseIntegrityError(str(exc)) from exc

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def configure_database(target):
    if is_postgres_target(target):
        return
    db_path = _sqlite_path(target)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path, timeout=BUSY_TIMEOUT_MS / 1000)
    try:
        conn.execute(f"PRAGMA busy_timeout = {BUSY_TIMEOUT_MS}")
        conn.execute("PRAGMA journal_mode = WAL")
        conn.execute("PRAGMA synchronous = NORMAL")
        conn.execute("PRAGMA foreign_keys = ON")
        conn.execute("PRAGMA wal_autocheckpoint = 1000")
    finally:
        conn.close()


@contextmanager
def connect(target):
    if is_postgres_target(target):
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:
            raise RuntimeError(
                "PostgreSQL yêu cầu package psycopg. Chạy: pip install -r requirements.txt"
            ) from exc
        raw = psycopg.connect(str(target), row_factory=dict_row)
        conn = PostgresConnectionAdapter(raw)
    else:
        db_path = _sqlite_path(target)
        db_path.parent.mkdir(parents=True, exist_ok=True)
        raw = sqlite3.connect(db_path, timeout=BUSY_TIMEOUT_MS / 1000)
        raw.row_factory = sqlite3.Row
        raw.execute(f"PRAGMA busy_timeout = {BUSY_TIMEOUT_MS}")
        raw.execute("PRAGMA foreign_keys = ON")
        conn = SQLiteConnectionAdapter(raw)

    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def table_exists(conn, table_name: str) -> bool:
    if getattr(conn, "backend_name", "sqlite") == "postgresql":
        row = conn.execute(
            """
            SELECT 1 AS found
            FROM information_schema.tables
            WHERE table_schema = current_schema() AND table_name = ?
            """,
            (table_name,),
        ).fetchone()
        return bool(row)
    return bool(conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name = ?",
        (table_name,),
    ).fetchone())


def table_columns(conn, table_name: str) -> list[str]:
    if getattr(conn, "backend_name", "sqlite") == "postgresql":
        rows = conn.execute(
            """
            SELECT column_name AS name
            FROM information_schema.columns
            WHERE table_schema = current_schema() AND table_name = ?
            ORDER BY ordinal_position
            """,
            (table_name,),
        ).fetchall()
    else:
        rows = conn.execute(f"PRAGMA table_info({table_name})").fetchall()
    return [row["name"] for row in rows]
