export const DEFAULT_COMPANY = {
  name: "Công ty Công nghệ DOMIX",
  address: "",
  phone: "",
  email: "",
  taxCode: "",
  representative: "",
  directorPasswordConfigured: false,
  establishedDate: "",
  registeredCharterCapital: 0,
  openingCashBalance: 0,
  taskReminderIntervalHours: 5,
};

export const ALL_APP_DATA_FIELDS = [
  "transactions", "orders", "marketingLogs", "debts", "inventory", "tasks", "lang", "company",
  "unlockedMonths", "capitalContributions", "distributionPartners", "distributionOrders",
  "payrollPayments", "kpiTiers", "cvReviews", "marketingPages", "contracts", "fixedAssets",
  "leads", "supportCases", "announcements", "chatMessages", "payrollApprovals",
  "midMonthRequests", "customers", "distributionSettlements", "stockMovements", "attendanceRequests",
  "paymentLedger", "securityAuditLog",
];

export const TAB_DEFAULT_FIELDS = {
  dashboard: [
    "transactions", "orders", "marketingLogs", "debts", "inventory", "stockMovements",
    "distributionOrders", "distributionSettlements", "payrollPayments", "payrollApprovals",
    "capitalContributions", "contracts", "leads", "cvReviews", "kpiTiers", "paymentLedger",
  ],
  settings: ["company", "announcements"],
  "task-reminder-settings": ["company"],
  thuchi: ["transactions", "orders", "marketingLogs", "payrollPayments", "debts", "paymentLedger"],
  congno: ["debts", "transactions", "orders", "paymentLedger", "distributionOrders", "distributionSettlements", "customers"],
  hopdong: ["contracts", "distributionPartners"],
  vongop: ["capitalContributions", "company", "transactions"],
  hoptac: ["distributionPartners", "distributionOrders", "distributionSettlements", "transactions", "debts", "orders", "inventory", "stockMovements"],
  kho: ["inventory", "stockMovements", "orders", "distributionOrders", "distributionPartners"],
  taisan: ["fixedAssets", "transactions"],
  giaoviec: ["tasks", "orders", "marketingLogs"],
  hotro: ["supportCases", "orders"],
  chat: ["tasks"],
  crm: ["transactions", "orders", "marketingLogs", "payrollPayments", "debts", "inventory", "stockMovements", "customers", "distributionOrders"],
  marketing: ["marketingLogs", "marketingPages", "orders", "inventory"],
  nhansu: [],
  tuyendung: ["cvReviews"],
  chamcong: ["unlockedMonths", "company", "attendanceRequests"],
  hieusuat: ["supportCases", "orders", "marketingLogs"],
  luong: ["payrollApprovals", "payrollPayments", "midMonthRequests", "transactions", "orders", "marketingLogs", "kpiTiers"],
  quy: ["transactions", "orders", "marketingLogs", "payrollPayments", "kpiTiers"],
  hoachdinh: ["transactions", "orders", "marketingLogs", "payrollPayments", "kpiTiers"],
  ai: ["transactions", "orders", "kpiTiers"],
  phaply: ["company", "contracts", "capitalContributions"],
  taikhoan: [],
};
